### ISSUE TITLE
Criar base_command

### ISSUE THREAD

**Issue by jesuejunior** [sievetech/rgc#1]
Criar requirements.
Criar arquivos:
               rgc.py
               main.py
               rules.py

Comando ficará:

``` bash
rgc  --username=USERRS --key=API_KEY  --days=NUMBER  --client=IDCLIENTE --type=TIPOEXPORTACAO
```

**Comment by thulio** [comment]
@jesuejunior O que você acha de passar as credenciais como variáveis de ambiente? Estilo Heroku

**Comment by etandel** [comment]
@thulio Uma boa; aí evitaria ficar no histórico... =D

Mas poderia ser um fallback, também: se não for passado na linha de comando, pega do ambiente.

**Comment by jesuejunior** [comment]
@thulio dei uma olhada aqui no heroku e conversando com o @etandel, podemos fazer o seguinte,

rgc login/auth/connect

abrirá um prompt solicitando o username e API_KEY, salvamos isso em um arquivo de '''config''' e usamos ela como variáveis("constantes"), mas também permitimos que seja passado via parâmetro, e cada pessoa que for usar terá que fazer essa '''config''' inicial e caso for usar um rackspace diferente tem a opção de usar no parâmetro, o que acha?
