### ISSUE TITLE
Add support to remove more than 10k objects

### ISSUE THREAD

**Issue by daltonmatos** [sievetech/rgc#15]
Rackspace limits the total number of objects in all collections to 10k. `rgc` should be able to detect if the container has more than 10k objects and redo the request to get more objects.

**Comment by etandel** [comment]
Does the API have a way to paginate the results?

**Comment by daltonmatos** [comment]
Yes: http://docs.rackspace.com/files/api/v1/cf-devguide/content/List_Large_Number_of_Containers-d1e1166.html

And I think that `delete_object()` (from python-cloudfiles) receives a keyword argument `marker`, to get objects _after_ that one.

The problem is that as we are removing objects from a container, I don't know how the API will behave if we pass a removed object as the `maker`.

**Comment by daltonmatos** [comment]
This is done.
