### ISSUE TITLE
Criar main.py

### ISSUE THREAD

**Issue by jesuejunior** [sievetech/rgc#4]
A main parseia os argumentos e chama a função exportada pelo rgc.py com os parâmetros.

**Comment by etandel** [comment]
A main já deverá instanciar o ruleset com as regras recebidas pelo shell, com o cuidade de não passar coisas como username e apikey. Algo como:

``` python
username = kwargs.pop('username')
apikey = kwargs.pop('apikey')
rg.collect(username, apikey, RuleSet(**kwargs))
```

Se o usuário passar regras que não existem, [problema dele](http://en.wikipedia.org/wiki/GIGO).
